# Generated by Django 4.2 on 2025-03-02 01:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_otp_user_is_email_verified_alter_user_email_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='monthly_installment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='tenure',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(3, message='Minimum tenure is 3 months'), django.core.validators.MaxValueValidator(24, message='Maximum tenure is 24 months')]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='installment_number',
            field=models.PositiveIntegerField(),
        ),
    ]
