# Generated by Django 4.2 on 2025-03-02 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_loan_monthly_installment_alter_loan_tenure_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('loan', 'installment_number')},
        ),
    ]
